[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "a49c2e55f365f08840c26a0e1164392add8f3126"
os = "macos"

    [[gh_cli.download]]
    sha256 = "e97d09c4dbeb1ca68d54dae5a515a280480a043a6c48e71a9f1abde6fb3ca386"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.aarch64-apple-darwin.tar.gz"
[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "c8a25c65148dd7252dc0a6a3bf9a5ca7fa332ba9"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "3e4d7b32c012b7d10d1ff474232709f253c221cafcbc98a3e41071ce6f34edb2"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.aarch64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "c8a25c65148dd7252dc0a6a3bf9a5ca7fa332ba9"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "3e4d7b32c012b7d10d1ff474232709f253c221cafcbc98a3e41071ce6f34edb2"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.aarch64-linux-musl.tar.gz"
[[gh_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d083767acfda637ea4008b410b82b24ea285a856"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "bf0bcac3501c93da936a1a750e505862b17f7035170fdb1eafbe160b0b8a0a15"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.armv6l-linux-gnueabihf.tar.gz"
[[gh_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d083767acfda637ea4008b410b82b24ea285a856"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "bf0bcac3501c93da936a1a750e505862b17f7035170fdb1eafbe160b0b8a0a15"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.armv6l-linux-musleabihf.tar.gz"
[[gh_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cca2bf9f50332a5c9c03e88a621631a64ef72b62"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "8441bfbc3d3a9c703df05dd3443b1fd0c2fc9560ebaec78177a55f4bf27bb420"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.armv7l-linux-gnueabihf.tar.gz"
[[gh_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cca2bf9f50332a5c9c03e88a621631a64ef72b62"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "8441bfbc3d3a9c703df05dd3443b1fd0c2fc9560ebaec78177a55f4bf27bb420"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.armv7l-linux-musleabihf.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "5e1f0efce8bd592c7faed40af7d1663d7fa9cc2f"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "6081e85695b1acf82610dfadfec7302c32528cdb17f406caedba27116673a596"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.i686-linux-gnu.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "5e1f0efce8bd592c7faed40af7d1663d7fa9cc2f"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "6081e85695b1acf82610dfadfec7302c32528cdb17f406caedba27116673a596"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.i686-linux-musl.tar.gz"
[[gh_cli]]
arch = "powerpc64le"
git-tree-sha1 = "c4e245bf5a420f587e497478da2ba29e297b4865"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "b373af3362cf461ad00e9007d1b42192a895abb7d61c399e5dfdd7d52eceb77d"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.powerpc64le-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "2db47415e9288543f7a6281da9f99be0fc68c037"
os = "macos"

    [[gh_cli.download]]
    sha256 = "f0362d271cfcee122506b7ec7e8fe75444875172cc90526b2f3015a37de9fedb"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.x86_64-apple-darwin.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "bb40ea37ebd5bdd16bfdecd86cead750706fb2af"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "c14257f8961ecded7cf549ebfbd0a5b5d778c8cecba637561bac9668cbe8b526"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.x86_64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "7d62534ff2a20a726dd3decc364e0ef775b5b6c8"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "e2b003181fc732b2171d1a137e51b8b6ae95c682258e5df19e499d53f6c62dc5"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.x86_64-linux-musl.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "58b1a18c9ed0d8f5db97225be69763c5764f3b4c"
os = "freebsd"

    [[gh_cli.download]]
    sha256 = "351c1f03efb252067e5ed1848d27dd43256265c382c3a9b70b5019aa42f1389f"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.44.1+0/gh_cli.v2.44.1.x86_64-unknown-freebsd.tar.gz"
