[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "9b70b7d4f0e16642984bef02e9f75febd3d25775"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "64433c7c693d2edd1adb6fbab85d49129a51ad3caa5166e64172317c85ae49cc"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.aarch64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "417e086fa29b32f8ab131137375474fbe2f9464c"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "bdfc6d99f495523aac487524f515ccaddef699c5559039a8a042c3ae1d047d80"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.aarch64-linux-musl.tar.gz"
[[gh_cli]]
arch = "armv7l"
git-tree-sha1 = "7c4c2828d5101da90f13ec38c46280040e372b03"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "d373c2c2dd8afee2ac75ac9ca184a246461426cdfc4dfd1ba6cb999ea1ad97a5"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[gh_cli]]
arch = "armv7l"
git-tree-sha1 = "f3bd25d19ef67022e434b371717b07359e3c7ad0"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "4108246d90252c37b577e211dc23774b13be6ada70b07b44b24da2777b8791b9"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "2dbdc43b6ffe82beed077ab950160c2dc91dbb64"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "635e0c1d177fb770d610fd4fdd68c604bc2bf1b6e4b9061e0135dfebc3267fd4"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.i686-linux-gnu.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "5a51d19ecbe76b45a9f0772099395131e76a5e72"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "d70a89045c77886530e7a90f99ff0f6dc1e9df1229197434d360d56c4133191b"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.i686-linux-musl.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "325ca18307e53666f1385a6c65926ff337f53756"
os = "windows"

    [[gh_cli.download]]
    sha256 = "382b7850970993c9bc6072a008b9c134ca6382dee6c46de0cfdd39161399f951"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.i686-w64-mingw32.tar.gz"
[[gh_cli]]
arch = "powerpc64le"
git-tree-sha1 = "e00335b17a50539dc58991a508d2b29abd309a48"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "00db7780a920b6551dd917cae4ddca8100b5d310cab1b9079a0a83e6a817a0ff"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "6b03c17f742d4ad512e690ea735284ab72be1896"
os = "macos"

    [[gh_cli.download]]
    sha256 = "ca4c19c505b59cad84846a43a1bceac0b2c08a48289512310f08ab5476a10838"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.x86_64-apple-darwin14.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "f7ad8f03cc74a246a08cd6dd66da22895ae6cd84"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "72bd905520d6235b0ce5301fd3e8421dd21fa46862bed3fcce56c5401040f650"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.x86_64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "e6c51e1a57d3bd28c5c7ce463a3863865c6f842e"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "0618e7f75f06ca8f2de7622edcc798ef6a00fb16349d1053786e7a767379ad66"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.x86_64-linux-musl.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "a4e6ddc87f20fe74e62d3e1bc812ef1ba3454449"
os = "freebsd"

    [[gh_cli.download]]
    sha256 = "fc5bfb1e3ac62bf4483030d28950432645b7eb83bf061eb105b8264464623140"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "c71cc24e8ff7ca7526a7b0caf576161fb2623e7e"
os = "windows"

    [[gh_cli.download]]
    sha256 = "069798b914c4705a27443ee3e6e69e8620029a63f45c54a3af8087ca566a9743"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v1.0.0+0/gh_cli.v1.0.0.x86_64-w64-mingw32.tar.gz"
