[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "80957be7779d2baf88c1fe5896524d4daa22c82c"
os = "macos"

    [[gh_cli.download]]
    sha256 = "9255b14f4d9062386714e254a100136f1c368e484c9496e001ca8cd20fcff4de"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.aarch64-apple-darwin.tar.gz"
[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "2a62f5170b9ffcd3d85dac99801c8ae44d485bce"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "213b364b649f787825ce861e164a4ab3895802c092aba759db2c682a2e5a302a"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.aarch64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "aarch64"
git-tree-sha1 = "2a62f5170b9ffcd3d85dac99801c8ae44d485bce"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "213b364b649f787825ce861e164a4ab3895802c092aba759db2c682a2e5a302a"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.aarch64-linux-musl.tar.gz"
[[gh_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41b09d14331a2d5050a8ceda85a5ae25988c6dbb"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "5413b6b171c9a8dc5a0f61711ec6cd6cf745d710835938fb8e17a6a3c771ad73"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.armv6l-linux-gnueabihf.tar.gz"
[[gh_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41b09d14331a2d5050a8ceda85a5ae25988c6dbb"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "5413b6b171c9a8dc5a0f61711ec6cd6cf745d710835938fb8e17a6a3c771ad73"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.armv6l-linux-musleabihf.tar.gz"
[[gh_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d60f86766a6969f33afc43b9acec310f4d1cc6bc"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "df2af09523450d08f53050a60fc3beddd76d5a1cf03657635828a89ae57fa71c"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.armv7l-linux-gnueabihf.tar.gz"
[[gh_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d60f86766a6969f33afc43b9acec310f4d1cc6bc"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "df2af09523450d08f53050a60fc3beddd76d5a1cf03657635828a89ae57fa71c"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.armv7l-linux-musleabihf.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "340a3762661434a20caeb331679191cbeb857c31"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "4a8452cba9cbc75069574e4965b9a75186ae775fb88769c1047f2b2d00b4b084"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.i686-linux-gnu.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "340a3762661434a20caeb331679191cbeb857c31"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "4a8452cba9cbc75069574e4965b9a75186ae775fb88769c1047f2b2d00b4b084"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.i686-linux-musl.tar.gz"
[[gh_cli]]
arch = "i686"
git-tree-sha1 = "9cc9266df371d582d3a58440039753ddc8f35195"
os = "windows"

    [[gh_cli.download]]
    sha256 = "3704f8e2285aa53ab34eb2a10515e04cdd999347b89047660bf801fbc4440960"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.i686-w64-mingw32.tar.gz"
[[gh_cli]]
arch = "powerpc64le"
git-tree-sha1 = "cde1bcf5c70e2a6fd2e1af1e94fe1c6261bddb14"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "6124face29ab1c6c730e6d8f7f77e759f3dabf4914a9cdff3994b7a57dda62ca"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.powerpc64le-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "173706df38b199e0cf8ab7fd87017e705eee886c"
os = "macos"

    [[gh_cli.download]]
    sha256 = "7d1d476a414eee8b41e55301871083a3f42b483b043214049ad5e323a93f633f"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.x86_64-apple-darwin.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "d4ec8a8a2a2f65f430668a337ed140226b8db7e3"
libc = "glibc"
os = "linux"

    [[gh_cli.download]]
    sha256 = "d79413b7899d97650269ca604dc147c3459d44165f582052638d18051c376402"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.x86_64-linux-gnu.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "88cebed1ca6e88c7e2de886d2c84de0f65e29a4a"
libc = "musl"
os = "linux"

    [[gh_cli.download]]
    sha256 = "66fa435f5469f87291a76f46539aeaafe6f1f0cf88f14cefedaf05d462d45066"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.x86_64-linux-musl.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "70bedbcced8da914b83da4b1c263679a62da6638"
os = "freebsd"

    [[gh_cli.download]]
    sha256 = "24b891091152664bfc2a6fa5ae3f450623d3b7105d5c21f467841dd6f6698c33"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.x86_64-unknown-freebsd.tar.gz"
[[gh_cli]]
arch = "x86_64"
git-tree-sha1 = "0322c02a28ce05d52433b660aad883b39c4da78d"
os = "windows"

    [[gh_cli.download]]
    sha256 = "9055091a83d3c0f0b3cf6d7796f965776147fa10b804e8811ba2164e9fd2e081"
    url = "https://github.com/JuliaBinaryWrappers/gh_cli_jll.jl/releases/download/gh_cli-v2.35.0+0/gh_cli.v2.35.0.x86_64-w64-mingw32.tar.gz"
