# Autogenerated wrapper script for gh_cli_jll for i686-linux-musl
export gh

JLLWrappers.@generate_wrapper_header("gh_cli")
JLLWrappers.@declare_executable_product(gh)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gh,
        "bin/gh",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
